Decrease error tolerance of 3dgut in test_rasterization tests
They are now quite good. If the tolerances are set to 0,
we get:

torch.testing.assert_close(renders, _renders, rtol=rtol, atol=atol)
AssertionError: Tensor-likes are not equal!
Mismatched elements: 3 / 1440000 (0.0%)
Greatest absolute difference: 1.3589859008789062e-05 at index (0, 0, 1, 53, 177, 2) (up to 1e-05 allowed)
Greatest relative difference: 2.1174439098103903e-05 at index (0, 0, 1, 53, 177, 2) (up to 1.3e-06 allowed)