[NV] Build system improvements and modular compilation (#878)
* Export types as module_local to avoid clashes with other modules

Without it, if another module also exposes a type, say, ShutterType,
we'd get this error:

ImportError: generic_type: type "ShutterType" is already registered!

Ref: https://pybind11.readthedocs.io/en/stable/advanced/classes.html#multiple-inheritance

* Build system improvements

* Simplification due to use of torch.utils.cpp_extension.load
* setup.py and JIT uses the exact same build parameters
* refactor handling of compiler flags
  - NO_FAST_MATH removed, use FAST_MATH=1/0 instead, default is 1.
  - Added DEBUG=1 to enable debug symbols in JIT compilation
  - FAST_COMPILE was dropped, should be DEBUG=1 instead.

* Enable c++20 mode

This change also removes support for precompiled headers.
Torch's cpp extensions build the pch assuming that we're using
c++17, but we're on c++20, hence the pch isn't picked up by gcc.

* JIT: rebuild if build parameters have changed

* jit: by default use all cores for building

Specify MAX_JOBS envvar if a limit is needed

* JIT: allow building of a subset of gsplat

The following envvars can be set:
BUILD_2DGS=1/0
BUILD_3DGS=1/0
BUILD_3DGUT=1/0
BUILD_ADAM=1/0
BUILD_RELOC=1/0

By default everything is built.
If one BUILD_* is set to 1, all others default
to 0 (i.e. aren't built).

* Add all missing dev/test dependencies to setup.py

* Add NUM_CHANNELS envvar to define the kernels instantiations to build

The corresponding macro is GSPLAT_NUM_CHANNELS. By default
(if nothing is defined), compile all number of channels that was
previously supported.

Tests only run with the needed subset of NUM_CHANNELS.
Also run tests with VERBOSE=1 by default.

Had to bump pytest to 7.1.3 due to the new dependency on pytest-env

* tests: clamp generated gaussian scales to min=1e-2

This avoids numerical instabilities in the gradients due to
1/scale term.

* test: relax quaternion gradient tolerance in projection test

Increase rtol from 0.2 to 0.3 and atol from 0.02 to 0.03 for
quaternion gradient comparison. This accounts for numerical
differences between CUDA (triu=True, triangular storage) and
PyTorch (triu=False, full 3x3 matrix) computation paths.

The paths are mathematically equivalent but have different
floating-point operation orders, causing 0.0001% of gradients
to exceed the previous tolerance by ~26%.

* build: only serialize build parameters to disk once

* build: do not use pickle to serialize build args

It's considered a security risk as it can execute
arbitrary code upon loading. Now we use json instead.

* Code formatting fixes