Export types as module_local to avoid clashes with other modules
Without it, if another module also exposes a type, say, ShutterType,
we'd get this error:

ImportError: generic_type: type "ShutterType" is already registered!

Ref: https://pybind11.readthedocs.io/en/stable/advanced/classes.html#multiple-inheritance